In [1]:
import numpy as np

In [73]:
d = 3
n = 5
x = np.random.rand(n, d)
y = np.random.randint(0, 2, (n))
epochs = 3
lr = .001

In [82]:
def predict(x, w, b):
    return np.transpose(1 / (1 + np.exp(-1*(np.matmul(x, w) + b))))

In [83]:
w = np.random.rand(d)
b = np.random.rand(1)

In [84]:
w

array([0.23429797, 0.84891235, 0.36906486])

In [85]:
x

array([[0.83365634, 0.83492578, 0.54588172],
       [0.21517   , 0.77664227, 0.84092641],
       [0.31365519, 0.53604642, 0.36368918],
       [0.43853121, 0.25053427, 0.64620666],
       [0.27942177, 0.69533464, 0.8179754 ]])

In [86]:
np.matmul(x, w)

array([1.10556855, 1.02007149, 0.6627701 , 0.55392077, 0.95763209])

In [87]:
predict(x, w, b)

array([0.86338336, 0.85298194, 0.80232374, 0.78449097, 0.844978  ])

In [89]:
for e in range(epochs):
    yhat = predict(x, w, b)
    gradw = 1/n * np.matmul(np.transpose(x), (yhat - y))
    w = w - lr * gradw
    gradb = 1/n * sum(yhat - y)
    b = b - lr * gradb
print(w, b)       

[0.23431699 0.84888832 0.36916835] [0.73802259]


In [90]:
xtest = np.random.rand(4,3)
ytest = predict(xtest, w, b)

In [91]:
ytest

array([0.85734091, 0.79191984, 0.8423234 , 0.86435679])

In [92]:
ytest[ytest>.5] = 1
ytest[ytest<=.5] = 0

In [93]:
ytest

array([1., 1., 1., 1.])