In [42]:

import numpy as np

In [45]:
np.random.seed(10)

In [48]:
X = np.random.rand(10, 3)

In [49]:
X

array([[0.8052232 , 0.52164715, 0.90864888],
       [0.31923609, 0.09045935, 0.30070006],
       [0.11398436, 0.82868133, 0.04689632],
       [0.62628715, 0.54758616, 0.819287  ],
       [0.19894754, 0.8568503 , 0.35165264],
       [0.75464769, 0.29596171, 0.88393648],
       [0.32551164, 0.1650159 , 0.39252924],
       [0.09346037, 0.82110566, 0.15115202],
       [0.38411445, 0.94426071, 0.98762547],
       [0.45630455, 0.82612284, 0.25137413]])

In [12]:
Y = np.random.randint(2, size=(10,1))

In [13]:
Y

array([[1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0]])

In [15]:
l = len(Y)

In [16]:
l

10

In [19]:
shuffled = np.random.shuffle(Y)

In [20]:
Y

array([[0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0]])

In [21]:
shuffled

In [22]:
indices = np.random.permutation(l)

In [23]:
indices

array([1, 7, 2, 6, 4, 5, 0, 3, 8, 9])

In [24]:
training_indices = indices[:8]
testing_indices = indices[8:]
trainx, textx = X[training_indices], X[testing_indices]

In [25]:
trainx

array([[0.5241661 , 0.62469768, 0.91243145],
       [0.10097825, 0.66203968, 0.21901235],
       [0.02422394, 0.18925103, 0.76605807],
       [0.83428049, 0.67726023, 0.2244986 ],
       [0.61861948, 0.25042403, 0.36532909],
       [0.75774147, 0.5571831 , 0.9577356 ],
       [0.89297461, 0.96123647, 0.38630283],
       [0.28378281, 0.49691945, 0.5894058 ]])

In [26]:
trainy, testy = Y[training_indices], Y[testing_indices]

In [27]:
trainy, testy

(array([[1],
        [0],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0]]),
 array([[1],
        [0]]))

In [28]:
w = np.random.rand(3,1)
b = 0

In [29]:
w, b

(array([[0.90350738],
        [0.62521266],
        [0.7467688 ]]),
 0)

In [54]:
xx = np.matmul(trainx, w) + b
act = 1. / (1 + np.exp(-1 * (np.matmul(trainx, w) + b)))
dr = np.multiply(act, (1-act))
der = np.multiply(der, trainx) 

In [55]:
xx, act, dr, der 

(array([[1.54553217],
        [0.66870178],
        [0.71227691],
        [1.34485879],
        [0.9883119 ],
        [1.74819001],
        [1.69626526],
        [1.00723006]]),
 array([[0.8242675 ],
        [0.6612124 ],
        [0.67090408],
        [0.79328783],
        [0.72875436],
        [0.85172436],
        [0.84504633],
        [0.73247772]]),
 array([[0.14485059],
        [0.22401056],
        [0.2207918 ],
        [0.16398225],
        [0.19767144],
        [0.12628997],
        [0.13094303],
        [0.19595411]]),
 array([[0.11734572, 0.13985185, 0.20426716],
        [0.01512616, 0.09917107, 0.03280723],
        [0.00380958, 0.02976254, 0.12047404],
        [0.18398635, 0.14935821, 0.04950934],
        [0.12085414, 0.0489231 , 0.07137107],
        [0.1672933 , 0.12301425, 0.21144778],
        [0.19834227, 0.21350419, 0.08580331],
        [0.05601046, 0.09807742, 0.11633154]]))

In [ ]:
epochs = 8
lr = .1
for epoch in range(epochs):
    # (n,1)
    summation = np.matmul(x, w) + b
    # (n, 1)
    sigmoid = 1. / (1 + np.exp(-1 * (np.matmul(trainx, w) + b)))
    # (n, 1)
    der = np.multiply(sigmoid *  (1 - sigmoid))
    # (n, k)
    gradw = np.multiply(der, trainx)
    # (1, k)
    gradwsum = np.sum(gradw, axis=0)
    # (1,1)
    gradbsum = np.sum(der)
    # (1, k)
    w = w - lr * gradwsum 